apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-app-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "configmaps"]
  verbs: ["list", "watch", "get"]